### ISSUE TITLE
Problemas ao tentar aplicar as coisas

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/articulacao-theme#12]
Matheus,

Não consegui entender porque depois de juntar tudo tenho resultados como esse ao cadastrar:
![articulacao-depois-registro](https://cloud.githubusercontent.com/assets/3632627/10467189/c80add96-71ce-11e5-9608-f11b0bd26ab8.png)

E ao logar como admin:

![form-sem-media-upload](https://cloud.githubusercontent.com/assets/3632627/10467196/cf51b7a0-71ce-11e5-9f7f-7555c0af0a68.png)

Tentei procurar um erro especifico, mas não consegui... O principal é o botão de upload de midia não funcionar.... Hora o site quebra inteiro tb... ta bizarro :(

**Comment by LuwkasLima** [comment]
@diegorojas se o site esta perfeito em nossa nuvem e voce fez a copia exata e configurou da mesma forma, talvez seja a hora de apresentarmos o cenario para a cliente. Talvez seja necessario pedirmos ajuda do pessoal da infra-estrutura. Pense nisso...

**Comment by matheusgimenez** [comment]
tudo funcionando no ultimo commit.. já joguei no beta.brasa

**Comment by diegorojas** [comment]
Então matheus, veja aqui que não consegui mesmo ainda cara... O erro que me aparece é esse aqui:

![sem-permissao](https://cloud.githubusercontent.com/assets/3632627/10489815/d596f41c-7274-11e5-9484-11be30ec1860.png)

Dessa forma não consigo subir a imagem. Ai a outra coisa é que de fato não está postando... Testado no Ubuntu e no windows com a mesma coisa... 

Dando uma olhada no log do Console veja:

![log-de-post-action](https://cloud.githubusercontent.com/assets/3632627/10489853/0bf65c50-7275-11e5-9642-537d57610ad6.png)

Acredito que têm mais coisa acontecendo por aqui man :(

**Comment by matheusgimenez** [comment]
feito no ultimo commit e já está no beta.brasa
